import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const adapter = new PrismaPg({ connectionString: process.env["DATABASE_URL"]! });
const prisma = new PrismaClient({ adapter } as ConstructorParameters<typeof PrismaClient>[0]);

// Source: WhatsJet data-schema.sql countries table (252 rows; ID 189 commented out in source)
// https://gist.github.com/paulochf/9616f85f3f3904f1c36f
const countries = [
  { id: 1, isoCode: "AF", nameCapitalized: "AFGHANISTAN", name: "Afghanistan", iso3Code: "AFG", isoNumCode: 4, phoneCode: 93 },
  { id: 2, isoCode: "AL", nameCapitalized: "ALBANIA", name: "Albania", iso3Code: "ALB", isoNumCode: 8, phoneCode: 355 },
  { id: 3, isoCode: "DZ", nameCapitalized: "ALGERIA", name: "Algeria", iso3Code: "DZA", isoNumCode: 12, phoneCode: 213 },
  { id: 4, isoCode: "AS", nameCapitalized: "AMERICAN SAMOA", name: "American Samoa", iso3Code: "ASM", isoNumCode: 16, phoneCode: 1684 },
  { id: 5, isoCode: "AD", nameCapitalized: "ANDORRA", name: "Andorra", iso3Code: "AND", isoNumCode: 20, phoneCode: 376 },
  { id: 6, isoCode: "AO", nameCapitalized: "ANGOLA", name: "Angola", iso3Code: "AGO", isoNumCode: 24, phoneCode: 244 },
  { id: 7, isoCode: "AI", nameCapitalized: "ANGUILLA", name: "Anguilla", iso3Code: "AIA", isoNumCode: 660, phoneCode: 1264 },
  { id: 8, isoCode: "AQ", nameCapitalized: "ANTARCTICA", name: "Antarctica", iso3Code: null, isoNumCode: null, phoneCode: 0 },
  { id: 9, isoCode: "AG", nameCapitalized: "ANTIGUA AND BARBUDA", name: "Antigua and Barbuda", iso3Code: "ATG", isoNumCode: 28, phoneCode: 1268 },
  { id: 10, isoCode: "AR", nameCapitalized: "ARGENTINA", name: "Argentina", iso3Code: "ARG", isoNumCode: 32, phoneCode: 54 },
  { id: 11, isoCode: "AM", nameCapitalized: "ARMENIA", name: "Armenia", iso3Code: "ARM", isoNumCode: 51, phoneCode: 374 },
  { id: 12, isoCode: "AW", nameCapitalized: "ARUBA", name: "Aruba", iso3Code: "ABW", isoNumCode: 533, phoneCode: 297 },
  { id: 13, isoCode: "AU", nameCapitalized: "AUSTRALIA", name: "Australia", iso3Code: "AUS", isoNumCode: 36, phoneCode: 61 },
  { id: 14, isoCode: "AT", nameCapitalized: "AUSTRIA", name: "Austria", iso3Code: "AUT", isoNumCode: 40, phoneCode: 43 },
  { id: 15, isoCode: "AZ", nameCapitalized: "AZERBAIJAN", name: "Azerbaijan", iso3Code: "AZE", isoNumCode: 31, phoneCode: 994 },
  { id: 16, isoCode: "BS", nameCapitalized: "BAHAMAS", name: "Bahamas", iso3Code: "BHS", isoNumCode: 44, phoneCode: 1242 },
  { id: 17, isoCode: "BH", nameCapitalized: "BAHRAIN", name: "Bahrain", iso3Code: "BHR", isoNumCode: 48, phoneCode: 973 },
  { id: 18, isoCode: "BD", nameCapitalized: "BANGLADESH", name: "Bangladesh", iso3Code: "BGD", isoNumCode: 50, phoneCode: 880 },
  { id: 19, isoCode: "BB", nameCapitalized: "BARBADOS", name: "Barbados", iso3Code: "BRB", isoNumCode: 52, phoneCode: 1246 },
  { id: 20, isoCode: "BY", nameCapitalized: "BELARUS", name: "Belarus", iso3Code: "BLR", isoNumCode: 112, phoneCode: 375 },
  { id: 21, isoCode: "BE", nameCapitalized: "BELGIUM", name: "Belgium", iso3Code: "BEL", isoNumCode: 56, phoneCode: 32 },
  { id: 22, isoCode: "BZ", nameCapitalized: "BELIZE", name: "Belize", iso3Code: "BLZ", isoNumCode: 84, phoneCode: 501 },
  { id: 23, isoCode: "BJ", nameCapitalized: "BENIN", name: "Benin", iso3Code: "BEN", isoNumCode: 204, phoneCode: 229 },
  { id: 24, isoCode: "BM", nameCapitalized: "BERMUDA", name: "Bermuda", iso3Code: "BMU", isoNumCode: 60, phoneCode: 1441 },
  { id: 25, isoCode: "BT", nameCapitalized: "BHUTAN", name: "Bhutan", iso3Code: "BTN", isoNumCode: 64, phoneCode: 975 },
  { id: 26, isoCode: "BO", nameCapitalized: "BOLIVIA", name: "Bolivia", iso3Code: "BOL", isoNumCode: 68, phoneCode: 591 },
  { id: 27, isoCode: "BA", nameCapitalized: "BOSNIA AND HERZEGOVINA", name: "Bosnia and Herzegovina", iso3Code: "BIH", isoNumCode: 70, phoneCode: 387 },
  { id: 28, isoCode: "BW", nameCapitalized: "BOTSWANA", name: "Botswana", iso3Code: "BWA", isoNumCode: 72, phoneCode: 267 },
  { id: 29, isoCode: "BV", nameCapitalized: "BOUVET ISLAND", name: "Bouvet Island", iso3Code: null, isoNumCode: null, phoneCode: 0 },
  { id: 30, isoCode: "BR", nameCapitalized: "BRAZIL", name: "Brazil", iso3Code: "BRA", isoNumCode: 76, phoneCode: 55 },
  { id: 31, isoCode: "IO", nameCapitalized: "BRITISH INDIAN OCEAN TERRITORY", name: "British Indian Ocean Territory", iso3Code: null, isoNumCode: null, phoneCode: 246 },
  { id: 32, isoCode: "BN", nameCapitalized: "BRUNEI DARUSSALAM", name: "Brunei Darussalam", iso3Code: "BRN", isoNumCode: 96, phoneCode: 673 },
  { id: 33, isoCode: "BG", nameCapitalized: "BULGARIA", name: "Bulgaria", iso3Code: "BGR", isoNumCode: 100, phoneCode: 359 },
  { id: 34, isoCode: "BF", nameCapitalized: "BURKINA FASO", name: "Burkina Faso", iso3Code: "BFA", isoNumCode: 854, phoneCode: 226 },
  { id: 35, isoCode: "BI", nameCapitalized: "BURUNDI", name: "Burundi", iso3Code: "BDI", isoNumCode: 108, phoneCode: 257 },
  { id: 36, isoCode: "KH", nameCapitalized: "CAMBODIA", name: "Cambodia", iso3Code: "KHM", isoNumCode: 116, phoneCode: 855 },
  { id: 37, isoCode: "CM", nameCapitalized: "CAMEROON", name: "Cameroon", iso3Code: "CMR", isoNumCode: 120, phoneCode: 237 },
  { id: 38, isoCode: "CA", nameCapitalized: "CANADA", name: "Canada", iso3Code: "CAN", isoNumCode: 124, phoneCode: 1 },
  { id: 39, isoCode: "CV", nameCapitalized: "CAPE VERDE", name: "Cape Verde", iso3Code: "CPV", isoNumCode: 132, phoneCode: 238 },
  { id: 40, isoCode: "KY", nameCapitalized: "CAYMAN ISLANDS", name: "Cayman Islands", iso3Code: "CYM", isoNumCode: 136, phoneCode: 1345 },
  { id: 41, isoCode: "CF", nameCapitalized: "CENTRAL AFRICAN REPUBLIC", name: "Central African Republic", iso3Code: "CAF", isoNumCode: 140, phoneCode: 236 },
  { id: 42, isoCode: "TD", nameCapitalized: "CHAD", name: "Chad", iso3Code: "TCD", isoNumCode: 148, phoneCode: 235 },
  { id: 43, isoCode: "CL", nameCapitalized: "CHILE", name: "Chile", iso3Code: "CHL", isoNumCode: 152, phoneCode: 56 },
  { id: 44, isoCode: "CN", nameCapitalized: "CHINA", name: "China", iso3Code: "CHN", isoNumCode: 156, phoneCode: 86 },
  { id: 45, isoCode: "CX", nameCapitalized: "CHRISTMAS ISLAND", name: "Christmas Island", iso3Code: null, isoNumCode: null, phoneCode: 61 },
  { id: 46, isoCode: "CC", nameCapitalized: "COCOS (KEELING) ISLANDS", name: "Cocos (Keeling) Islands", iso3Code: null, isoNumCode: null, phoneCode: 672 },
  { id: 47, isoCode: "CO", nameCapitalized: "COLOMBIA", name: "Colombia", iso3Code: "COL", isoNumCode: 170, phoneCode: 57 },
  { id: 48, isoCode: "KM", nameCapitalized: "COMOROS", name: "Comoros", iso3Code: "COM", isoNumCode: 174, phoneCode: 269 },
  { id: 49, isoCode: "CG", nameCapitalized: "CONGO", name: "Congo", iso3Code: "COG", isoNumCode: 178, phoneCode: 242 },
  { id: 50, isoCode: "CD", nameCapitalized: "CONGO, THE DEMOCRATIC REPUBLIC OF THE", name: "Congo, the Democratic Republic of the", iso3Code: "COD", isoNumCode: 180, phoneCode: 243 },
  { id: 51, isoCode: "CK", nameCapitalized: "COOK ISLANDS", name: "Cook Islands", iso3Code: "COK", isoNumCode: 184, phoneCode: 682 },
  { id: 52, isoCode: "CR", nameCapitalized: "COSTA RICA", name: "Costa Rica", iso3Code: "CRI", isoNumCode: 188, phoneCode: 506 },
  { id: 53, isoCode: "CI", nameCapitalized: "COTE D'IVOIRE", name: "Cote D'Ivoire", iso3Code: "CIV", isoNumCode: 384, phoneCode: 225 },
  { id: 54, isoCode: "HR", nameCapitalized: "CROATIA", name: "Croatia", iso3Code: "HRV", isoNumCode: 191, phoneCode: 385 },
  { id: 55, isoCode: "CU", nameCapitalized: "CUBA", name: "Cuba", iso3Code: "CUB", isoNumCode: 192, phoneCode: 53 },
  { id: 56, isoCode: "CY", nameCapitalized: "CYPRUS", name: "Cyprus", iso3Code: "CYP", isoNumCode: 196, phoneCode: 357 },
  { id: 57, isoCode: "CZ", nameCapitalized: "CZECH REPUBLIC", name: "Czech Republic", iso3Code: "CZE", isoNumCode: 203, phoneCode: 420 },
  { id: 58, isoCode: "DK", nameCapitalized: "DENMARK", name: "Denmark", iso3Code: "DNK", isoNumCode: 208, phoneCode: 45 },
  { id: 59, isoCode: "DJ", nameCapitalized: "DJIBOUTI", name: "Djibouti", iso3Code: "DJI", isoNumCode: 262, phoneCode: 253 },
  { id: 60, isoCode: "DM", nameCapitalized: "DOMINICA", name: "Dominica", iso3Code: "DMA", isoNumCode: 212, phoneCode: 1767 },
  { id: 61, isoCode: "DO", nameCapitalized: "DOMINICAN REPUBLIC", name: "Dominican Republic", iso3Code: "DOM", isoNumCode: 214, phoneCode: 1809 },
  { id: 62, isoCode: "EC", nameCapitalized: "ECUADOR", name: "Ecuador", iso3Code: "ECU", isoNumCode: 218, phoneCode: 593 },
  { id: 63, isoCode: "EG", nameCapitalized: "EGYPT", name: "Egypt", iso3Code: "EGY", isoNumCode: 818, phoneCode: 20 },
  { id: 64, isoCode: "SV", nameCapitalized: "EL SALVADOR", name: "El Salvador", iso3Code: "SLV", isoNumCode: 222, phoneCode: 503 },
  { id: 65, isoCode: "GQ", nameCapitalized: "EQUATORIAL GUINEA", name: "Equatorial Guinea", iso3Code: "GNQ", isoNumCode: 226, phoneCode: 240 },
  { id: 66, isoCode: "ER", nameCapitalized: "ERITREA", name: "Eritrea", iso3Code: "ERI", isoNumCode: 232, phoneCode: 291 },
  { id: 67, isoCode: "EE", nameCapitalized: "ESTONIA", name: "Estonia", iso3Code: "EST", isoNumCode: 233, phoneCode: 372 },
  { id: 68, isoCode: "ET", nameCapitalized: "ETHIOPIA", name: "Ethiopia", iso3Code: "ETH", isoNumCode: 231, phoneCode: 251 },
  { id: 69, isoCode: "FK", nameCapitalized: "FALKLAND ISLANDS (MALVINAS)", name: "Falkland Islands (Malvinas)", iso3Code: "FLK", isoNumCode: 238, phoneCode: 500 },
  { id: 70, isoCode: "FO", nameCapitalized: "FAROE ISLANDS", name: "Faroe Islands", iso3Code: "FRO", isoNumCode: 234, phoneCode: 298 },
  { id: 71, isoCode: "FJ", nameCapitalized: "FIJI", name: "Fiji", iso3Code: "FJI", isoNumCode: 242, phoneCode: 679 },
  { id: 72, isoCode: "FI", nameCapitalized: "FINLAND", name: "Finland", iso3Code: "FIN", isoNumCode: 246, phoneCode: 358 },
  { id: 73, isoCode: "FR", nameCapitalized: "FRANCE", name: "France", iso3Code: "FRA", isoNumCode: 250, phoneCode: 33 },
  { id: 74, isoCode: "GF", nameCapitalized: "FRENCH GUIANA", name: "French Guiana", iso3Code: "GUF", isoNumCode: 254, phoneCode: 594 },
  { id: 75, isoCode: "PF", nameCapitalized: "FRENCH POLYNESIA", name: "French Polynesia", iso3Code: "PYF", isoNumCode: 258, phoneCode: 689 },
  { id: 76, isoCode: "TF", nameCapitalized: "FRENCH SOUTHERN TERRITORIES", name: "French Southern Territories", iso3Code: null, isoNumCode: null, phoneCode: 0 },
  { id: 77, isoCode: "GA", nameCapitalized: "GABON", name: "Gabon", iso3Code: "GAB", isoNumCode: 266, phoneCode: 241 },
  { id: 78, isoCode: "GM", nameCapitalized: "GAMBIA", name: "Gambia", iso3Code: "GMB", isoNumCode: 270, phoneCode: 220 },
  { id: 79, isoCode: "GE", nameCapitalized: "GEORGIA", name: "Georgia", iso3Code: "GEO", isoNumCode: 268, phoneCode: 995 },
  { id: 80, isoCode: "DE", nameCapitalized: "GERMANY", name: "Germany", iso3Code: "DEU", isoNumCode: 276, phoneCode: 49 },
  { id: 81, isoCode: "GH", nameCapitalized: "GHANA", name: "Ghana", iso3Code: "GHA", isoNumCode: 288, phoneCode: 233 },
  { id: 82, isoCode: "GI", nameCapitalized: "GIBRALTAR", name: "Gibraltar", iso3Code: "GIB", isoNumCode: 292, phoneCode: 350 },
  { id: 83, isoCode: "GR", nameCapitalized: "GREECE", name: "Greece", iso3Code: "GRC", isoNumCode: 300, phoneCode: 30 },
  { id: 84, isoCode: "GL", nameCapitalized: "GREENLAND", name: "Greenland", iso3Code: "GRL", isoNumCode: 304, phoneCode: 299 },
  { id: 85, isoCode: "GD", nameCapitalized: "GRENADA", name: "Grenada", iso3Code: "GRD", isoNumCode: 308, phoneCode: 1473 },
  { id: 86, isoCode: "GP", nameCapitalized: "GUADELOUPE", name: "Guadeloupe", iso3Code: "GLP", isoNumCode: 312, phoneCode: 590 },
  { id: 87, isoCode: "GU", nameCapitalized: "GUAM", name: "Guam", iso3Code: "GUM", isoNumCode: 316, phoneCode: 1671 },
  { id: 88, isoCode: "GT", nameCapitalized: "GUATEMALA", name: "Guatemala", iso3Code: "GTM", isoNumCode: 320, phoneCode: 502 },
  { id: 89, isoCode: "GN", nameCapitalized: "GUINEA", name: "Guinea", iso3Code: "GIN", isoNumCode: 324, phoneCode: 224 },
  { id: 90, isoCode: "GW", nameCapitalized: "GUINEA-BISSAU", name: "Guinea-Bissau", iso3Code: "GNB", isoNumCode: 624, phoneCode: 245 },
  { id: 91, isoCode: "GY", nameCapitalized: "GUYANA", name: "Guyana", iso3Code: "GUY", isoNumCode: 328, phoneCode: 592 },
  { id: 92, isoCode: "HT", nameCapitalized: "HAITI", name: "Haiti", iso3Code: "HTI", isoNumCode: 332, phoneCode: 509 },
  { id: 93, isoCode: "HM", nameCapitalized: "HEARD ISLAND AND MCDONALD ISLANDS", name: "Heard Island and Mcdonald Islands", iso3Code: null, isoNumCode: null, phoneCode: 0 },
  { id: 94, isoCode: "VA", nameCapitalized: "HOLY SEE (VATICAN CITY STATE)", name: "Holy See (Vatican City State)", iso3Code: "VAT", isoNumCode: 336, phoneCode: 39 },
  { id: 95, isoCode: "HN", nameCapitalized: "HONDURAS", name: "Honduras", iso3Code: "HND", isoNumCode: 340, phoneCode: 504 },
  { id: 96, isoCode: "HK", nameCapitalized: "HONG KONG", name: "Hong Kong", iso3Code: "HKG", isoNumCode: 344, phoneCode: 852 },
  { id: 97, isoCode: "HU", nameCapitalized: "HUNGARY", name: "Hungary", iso3Code: "HUN", isoNumCode: 348, phoneCode: 36 },
  { id: 98, isoCode: "IS", nameCapitalized: "ICELAND", name: "Iceland", iso3Code: "ISL", isoNumCode: 352, phoneCode: 354 },
  { id: 99, isoCode: "IN", nameCapitalized: "INDIA", name: "India", iso3Code: "IND", isoNumCode: 356, phoneCode: 91 },
  { id: 100, isoCode: "ID", nameCapitalized: "INDONESIA", name: "Indonesia", iso3Code: "IDN", isoNumCode: 360, phoneCode: 62 },
  { id: 101, isoCode: "IR", nameCapitalized: "IRAN, ISLAMIC REPUBLIC OF", name: "Iran, Islamic Republic of", iso3Code: "IRN", isoNumCode: 364, phoneCode: 98 },
  { id: 102, isoCode: "IQ", nameCapitalized: "IRAQ", name: "Iraq", iso3Code: "IRQ", isoNumCode: 368, phoneCode: 964 },
  { id: 103, isoCode: "IE", nameCapitalized: "IRELAND", name: "Ireland", iso3Code: "IRL", isoNumCode: 372, phoneCode: 353 },
  { id: 104, isoCode: "IL", nameCapitalized: "ISRAEL", name: "Israel", iso3Code: "ISR", isoNumCode: 376, phoneCode: 972 },
  { id: 105, isoCode: "IT", nameCapitalized: "ITALY", name: "Italy", iso3Code: "ITA", isoNumCode: 380, phoneCode: 39 },
  { id: 106, isoCode: "JM", nameCapitalized: "JAMAICA", name: "Jamaica", iso3Code: "JAM", isoNumCode: 388, phoneCode: 1876 },
  { id: 107, isoCode: "JP", nameCapitalized: "JAPAN", name: "Japan", iso3Code: "JPN", isoNumCode: 392, phoneCode: 81 },
  { id: 108, isoCode: "JO", nameCapitalized: "JORDAN", name: "Jordan", iso3Code: "JOR", isoNumCode: 400, phoneCode: 962 },
  { id: 109, isoCode: "KZ", nameCapitalized: "KAZAKHSTAN", name: "Kazakhstan", iso3Code: "KAZ", isoNumCode: 398, phoneCode: 7 },
  { id: 110, isoCode: "KE", nameCapitalized: "KENYA", name: "Kenya", iso3Code: "KEN", isoNumCode: 404, phoneCode: 254 },
  { id: 111, isoCode: "KI", nameCapitalized: "KIRIBATI", name: "Kiribati", iso3Code: "KIR", isoNumCode: 296, phoneCode: 686 },
  { id: 112, isoCode: "KP", nameCapitalized: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", name: "Korea, Democratic People's Republic of", iso3Code: "PRK", isoNumCode: 408, phoneCode: 850 },
  { id: 113, isoCode: "KR", nameCapitalized: "KOREA, REPUBLIC OF", name: "Korea, Republic of", iso3Code: "KOR", isoNumCode: 410, phoneCode: 82 },
  { id: 114, isoCode: "KW", nameCapitalized: "KUWAIT", name: "Kuwait", iso3Code: "KWT", isoNumCode: 414, phoneCode: 965 },
  { id: 115, isoCode: "KG", nameCapitalized: "KYRGYZSTAN", name: "Kyrgyzstan", iso3Code: "KGZ", isoNumCode: 417, phoneCode: 996 },
  { id: 116, isoCode: "LA", nameCapitalized: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", name: "Lao People's Democratic Republic", iso3Code: "LAO", isoNumCode: 418, phoneCode: 856 },
  { id: 117, isoCode: "LV", nameCapitalized: "LATVIA", name: "Latvia", iso3Code: "LVA", isoNumCode: 428, phoneCode: 371 },
  { id: 118, isoCode: "LB", nameCapitalized: "LEBANON", name: "Lebanon", iso3Code: "LBN", isoNumCode: 422, phoneCode: 961 },
  { id: 119, isoCode: "LS", nameCapitalized: "LESOTHO", name: "Lesotho", iso3Code: "LSO", isoNumCode: 426, phoneCode: 266 },
  { id: 120, isoCode: "LR", nameCapitalized: "LIBERIA", name: "Liberia", iso3Code: "LBR", isoNumCode: 430, phoneCode: 231 },
  { id: 121, isoCode: "LY", nameCapitalized: "LIBYAN ARAB JAMAHIRIYA", name: "Libyan Arab Jamahiriya", iso3Code: "LBY", isoNumCode: 434, phoneCode: 218 },
  { id: 122, isoCode: "LI", nameCapitalized: "LIECHTENSTEIN", name: "Liechtenstein", iso3Code: "LIE", isoNumCode: 438, phoneCode: 423 },
  { id: 123, isoCode: "LT", nameCapitalized: "LITHUANIA", name: "Lithuania", iso3Code: "LTU", isoNumCode: 440, phoneCode: 370 },
  { id: 124, isoCode: "LU", nameCapitalized: "LUXEMBOURG", name: "Luxembourg", iso3Code: "LUX", isoNumCode: 442, phoneCode: 352 },
  { id: 125, isoCode: "MO", nameCapitalized: "MACAO", name: "Macao", iso3Code: "MAC", isoNumCode: 446, phoneCode: 853 },
  { id: 126, isoCode: "MK", nameCapitalized: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", name: "Macedonia, the Former Yugoslav Republic of", iso3Code: "MKD", isoNumCode: 807, phoneCode: 389 },
  { id: 127, isoCode: "MG", nameCapitalized: "MADAGASCAR", name: "Madagascar", iso3Code: "MDG", isoNumCode: 450, phoneCode: 261 },
  { id: 128, isoCode: "MW", nameCapitalized: "MALAWI", name: "Malawi", iso3Code: "MWI", isoNumCode: 454, phoneCode: 265 },
  { id: 129, isoCode: "MY", nameCapitalized: "MALAYSIA", name: "Malaysia", iso3Code: "MYS", isoNumCode: 458, phoneCode: 60 },
  { id: 130, isoCode: "MV", nameCapitalized: "MALDIVES", name: "Maldives", iso3Code: "MDV", isoNumCode: 462, phoneCode: 960 },
  { id: 131, isoCode: "ML", nameCapitalized: "MALI", name: "Mali", iso3Code: "MLI", isoNumCode: 466, phoneCode: 223 },
  { id: 132, isoCode: "MT", nameCapitalized: "MALTA", name: "Malta", iso3Code: "MLT", isoNumCode: 470, phoneCode: 356 },
  { id: 133, isoCode: "MH", nameCapitalized: "MARSHALL ISLANDS", name: "Marshall Islands", iso3Code: "MHL", isoNumCode: 584, phoneCode: 692 },
  { id: 134, isoCode: "MQ", nameCapitalized: "MARTINIQUE", name: "Martinique", iso3Code: "MTQ", isoNumCode: 474, phoneCode: 596 },
  { id: 135, isoCode: "MR", nameCapitalized: "MAURITANIA", name: "Mauritania", iso3Code: "MRT", isoNumCode: 478, phoneCode: 222 },
  { id: 136, isoCode: "MU", nameCapitalized: "MAURITIUS", name: "Mauritius", iso3Code: "MUS", isoNumCode: 480, phoneCode: 230 },
  { id: 137, isoCode: "YT", nameCapitalized: "MAYOTTE", name: "Mayotte", iso3Code: null, isoNumCode: null, phoneCode: 269 },
  { id: 138, isoCode: "MX", nameCapitalized: "MEXICO", name: "Mexico", iso3Code: "MEX", isoNumCode: 484, phoneCode: 52 },
  { id: 139, isoCode: "FM", nameCapitalized: "MICRONESIA, FEDERATED STATES OF", name: "Micronesia, Federated States of", iso3Code: "FSM", isoNumCode: 583, phoneCode: 691 },
  { id: 140, isoCode: "MD", nameCapitalized: "MOLDOVA, REPUBLIC OF", name: "Moldova, Republic of", iso3Code: "MDA", isoNumCode: 498, phoneCode: 373 },
  { id: 141, isoCode: "MC", nameCapitalized: "MONACO", name: "Monaco", iso3Code: "MCO", isoNumCode: 492, phoneCode: 377 },
  { id: 142, isoCode: "MN", nameCapitalized: "MONGOLIA", name: "Mongolia", iso3Code: "MNG", isoNumCode: 496, phoneCode: 976 },
  { id: 143, isoCode: "MS", nameCapitalized: "MONTSERRAT", name: "Montserrat", iso3Code: "MSR", isoNumCode: 500, phoneCode: 1664 },
  { id: 144, isoCode: "MA", nameCapitalized: "MOROCCO", name: "Morocco", iso3Code: "MAR", isoNumCode: 504, phoneCode: 212 },
  { id: 145, isoCode: "MZ", nameCapitalized: "MOZAMBIQUE", name: "Mozambique", iso3Code: "MOZ", isoNumCode: 508, phoneCode: 258 },
  { id: 146, isoCode: "MM", nameCapitalized: "MYANMAR", name: "Myanmar", iso3Code: "MMR", isoNumCode: 104, phoneCode: 95 },
  { id: 147, isoCode: "NA", nameCapitalized: "NAMIBIA", name: "Namibia", iso3Code: "NAM", isoNumCode: 516, phoneCode: 264 },
  { id: 148, isoCode: "NR", nameCapitalized: "NAURU", name: "Nauru", iso3Code: "NRU", isoNumCode: 520, phoneCode: 674 },
  { id: 149, isoCode: "NP", nameCapitalized: "NEPAL", name: "Nepal", iso3Code: "NPL", isoNumCode: 524, phoneCode: 977 },
  { id: 150, isoCode: "NL", nameCapitalized: "NETHERLANDS", name: "Netherlands", iso3Code: "NLD", isoNumCode: 528, phoneCode: 31 },
  { id: 151, isoCode: "AN", nameCapitalized: "NETHERLANDS ANTILLES", name: "Netherlands Antilles", iso3Code: "ANT", isoNumCode: 530, phoneCode: 599 },
  { id: 152, isoCode: "NC", nameCapitalized: "NEW CALEDONIA", name: "New Caledonia", iso3Code: "NCL", isoNumCode: 540, phoneCode: 687 },
  { id: 153, isoCode: "NZ", nameCapitalized: "NEW ZEALAND", name: "New Zealand", iso3Code: "NZL", isoNumCode: 554, phoneCode: 64 },
  { id: 154, isoCode: "NI", nameCapitalized: "NICARAGUA", name: "Nicaragua", iso3Code: "NIC", isoNumCode: 558, phoneCode: 505 },
  { id: 155, isoCode: "NE", nameCapitalized: "NIGER", name: "Niger", iso3Code: "NER", isoNumCode: 562, phoneCode: 227 },
  { id: 156, isoCode: "NG", nameCapitalized: "NIGERIA", name: "Nigeria", iso3Code: "NGA", isoNumCode: 566, phoneCode: 234 },
  { id: 157, isoCode: "NU", nameCapitalized: "NIUE", name: "Niue", iso3Code: "NIU", isoNumCode: 570, phoneCode: 683 },
  { id: 158, isoCode: "NF", nameCapitalized: "NORFOLK ISLAND", name: "Norfolk Island", iso3Code: "NFK", isoNumCode: 574, phoneCode: 672 },
  { id: 159, isoCode: "MP", nameCapitalized: "NORTHERN MARIANA ISLANDS", name: "Northern Mariana Islands", iso3Code: "MNP", isoNumCode: 580, phoneCode: 1670 },
  { id: 160, isoCode: "NO", nameCapitalized: "NORWAY", name: "Norway", iso3Code: "NOR", isoNumCode: 578, phoneCode: 47 },
  { id: 161, isoCode: "OM", nameCapitalized: "OMAN", name: "Oman", iso3Code: "OMN", isoNumCode: 512, phoneCode: 968 },
  { id: 162, isoCode: "PK", nameCapitalized: "PAKISTAN", name: "Pakistan", iso3Code: "PAK", isoNumCode: 586, phoneCode: 92 },
  { id: 163, isoCode: "PW", nameCapitalized: "PALAU", name: "Palau", iso3Code: "PLW", isoNumCode: 585, phoneCode: 680 },
  { id: 164, isoCode: "PS", nameCapitalized: "PALESTINIAN TERRITORY, OCCUPIED", name: "Palestinian Territory, Occupied", iso3Code: null, isoNumCode: null, phoneCode: 970 },
  { id: 165, isoCode: "PA", nameCapitalized: "PANAMA", name: "Panama", iso3Code: "PAN", isoNumCode: 591, phoneCode: 507 },
  { id: 166, isoCode: "PG", nameCapitalized: "PAPUA NEW GUINEA", name: "Papua New Guinea", iso3Code: "PNG", isoNumCode: 598, phoneCode: 675 },
  { id: 167, isoCode: "PY", nameCapitalized: "PARAGUAY", name: "Paraguay", iso3Code: "PRY", isoNumCode: 600, phoneCode: 595 },
  { id: 168, isoCode: "PE", nameCapitalized: "PERU", name: "Peru", iso3Code: "PER", isoNumCode: 604, phoneCode: 51 },
  { id: 169, isoCode: "PH", nameCapitalized: "PHILIPPINES", name: "Philippines", iso3Code: "PHL", isoNumCode: 608, phoneCode: 63 },
  { id: 170, isoCode: "PN", nameCapitalized: "PITCAIRN", name: "Pitcairn", iso3Code: "PCN", isoNumCode: 612, phoneCode: 0 },
  { id: 171, isoCode: "PL", nameCapitalized: "POLAND", name: "Poland", iso3Code: "POL", isoNumCode: 616, phoneCode: 48 },
  { id: 172, isoCode: "PT", nameCapitalized: "PORTUGAL", name: "Portugal", iso3Code: "PRT", isoNumCode: 620, phoneCode: 351 },
  { id: 173, isoCode: "PR", nameCapitalized: "PUERTO RICO", name: "Puerto Rico", iso3Code: "PRI", isoNumCode: 630, phoneCode: 1787 },
  { id: 174, isoCode: "QA", nameCapitalized: "QATAR", name: "Qatar", iso3Code: "QAT", isoNumCode: 634, phoneCode: 974 },
  { id: 175, isoCode: "RE", nameCapitalized: "REUNION", name: "Reunion", iso3Code: "REU", isoNumCode: 638, phoneCode: 262 },
  { id: 176, isoCode: "RO", nameCapitalized: "ROMANIA", name: "Romania", iso3Code: "ROM", isoNumCode: 642, phoneCode: 40 },
  { id: 177, isoCode: "RU", nameCapitalized: "RUSSIAN FEDERATION", name: "Russian Federation", iso3Code: "RUS", isoNumCode: 643, phoneCode: 7 },
  { id: 178, isoCode: "RW", nameCapitalized: "RWANDA", name: "Rwanda", iso3Code: "RWA", isoNumCode: 646, phoneCode: 250 },
  { id: 179, isoCode: "SH", nameCapitalized: "SAINT HELENA", name: "Saint Helena", iso3Code: "SHN", isoNumCode: 654, phoneCode: 290 },
  { id: 180, isoCode: "KN", nameCapitalized: "SAINT KITTS AND NEVIS", name: "Saint Kitts and Nevis", iso3Code: "KNA", isoNumCode: 659, phoneCode: 1869 },
  { id: 181, isoCode: "LC", nameCapitalized: "SAINT LUCIA", name: "Saint Lucia", iso3Code: "LCA", isoNumCode: 662, phoneCode: 1758 },
  { id: 182, isoCode: "PM", nameCapitalized: "SAINT PIERRE AND MIQUELON", name: "Saint Pierre and Miquelon", iso3Code: "SPM", isoNumCode: 666, phoneCode: 508 },
  { id: 183, isoCode: "VC", nameCapitalized: "SAINT VINCENT AND THE GRENADINES", name: "Saint Vincent and the Grenadines", iso3Code: "VCT", isoNumCode: 670, phoneCode: 1784 },
  { id: 184, isoCode: "WS", nameCapitalized: "SAMOA", name: "Samoa", iso3Code: "WSM", isoNumCode: 882, phoneCode: 684 },
  { id: 185, isoCode: "SM", nameCapitalized: "SAN MARINO", name: "San Marino", iso3Code: "SMR", isoNumCode: 674, phoneCode: 378 },
  { id: 186, isoCode: "ST", nameCapitalized: "SAO TOME AND PRINCIPE", name: "Sao Tome and Principe", iso3Code: "STP", isoNumCode: 678, phoneCode: 239 },
  { id: 187, isoCode: "SA", nameCapitalized: "SAUDI ARABIA", name: "Saudi Arabia", iso3Code: "SAU", isoNumCode: 682, phoneCode: 966 },
  { id: 188, isoCode: "SN", nameCapitalized: "SENEGAL", name: "Senegal", iso3Code: "SEN", isoNumCode: 686, phoneCode: 221 },
  { id: 190, isoCode: "SC", nameCapitalized: "SEYCHELLES", name: "Seychelles", iso3Code: "SYC", isoNumCode: 690, phoneCode: 248 },
  { id: 191, isoCode: "SL", nameCapitalized: "SIERRA LEONE", name: "Sierra Leone", iso3Code: "SLE", isoNumCode: 694, phoneCode: 232 },
  { id: 192, isoCode: "SG", nameCapitalized: "SINGAPORE", name: "Singapore", iso3Code: "SGP", isoNumCode: 702, phoneCode: 65 },
  { id: 193, isoCode: "SK", nameCapitalized: "SLOVAKIA", name: "Slovakia", iso3Code: "SVK", isoNumCode: 703, phoneCode: 421 },
  { id: 194, isoCode: "SI", nameCapitalized: "SLOVENIA", name: "Slovenia", iso3Code: "SVN", isoNumCode: 705, phoneCode: 386 },
  { id: 195, isoCode: "SB", nameCapitalized: "SOLOMON ISLANDS", name: "Solomon Islands", iso3Code: "SLB", isoNumCode: 90, phoneCode: 677 },
  { id: 196, isoCode: "SO", nameCapitalized: "SOMALIA", name: "Somalia", iso3Code: "SOM", isoNumCode: 706, phoneCode: 252 },
  { id: 197, isoCode: "ZA", nameCapitalized: "SOUTH AFRICA", name: "South Africa", iso3Code: "ZAF", isoNumCode: 710, phoneCode: 27 },
  { id: 198, isoCode: "GS", nameCapitalized: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", name: "South Georgia and the South Sandwich Islands", iso3Code: null, isoNumCode: null, phoneCode: 0 },
  { id: 199, isoCode: "ES", nameCapitalized: "SPAIN", name: "Spain", iso3Code: "ESP", isoNumCode: 724, phoneCode: 34 },
  { id: 200, isoCode: "LK", nameCapitalized: "SRI LANKA", name: "Sri Lanka", iso3Code: "LKA", isoNumCode: 144, phoneCode: 94 },
  { id: 201, isoCode: "SD", nameCapitalized: "SUDAN", name: "Sudan", iso3Code: "SDN", isoNumCode: 736, phoneCode: 249 },
  { id: 202, isoCode: "SR", nameCapitalized: "SURINAME", name: "Suriname", iso3Code: "SUR", isoNumCode: 740, phoneCode: 597 },
  { id: 203, isoCode: "SJ", nameCapitalized: "SVALBARD AND JAN MAYEN", name: "Svalbard and Jan Mayen", iso3Code: "SJM", isoNumCode: 744, phoneCode: 47 },
  { id: 204, isoCode: "SZ", nameCapitalized: "SWAZILAND", name: "Swaziland", iso3Code: "SWZ", isoNumCode: 748, phoneCode: 268 },
  { id: 205, isoCode: "SE", nameCapitalized: "SWEDEN", name: "Sweden", iso3Code: "SWE", isoNumCode: 752, phoneCode: 46 },
  { id: 206, isoCode: "CH", nameCapitalized: "SWITZERLAND", name: "Switzerland", iso3Code: "CHE", isoNumCode: 756, phoneCode: 41 },
  { id: 207, isoCode: "SY", nameCapitalized: "SYRIAN ARAB REPUBLIC", name: "Syrian Arab Republic", iso3Code: "SYR", isoNumCode: 760, phoneCode: 963 },
  { id: 208, isoCode: "TW", nameCapitalized: "TAIWAN, PROVINCE OF CHINA", name: "Taiwan, Province of China", iso3Code: "TWN", isoNumCode: 158, phoneCode: 886 },
  { id: 209, isoCode: "TJ", nameCapitalized: "TAJIKISTAN", name: "Tajikistan", iso3Code: "TJK", isoNumCode: 762, phoneCode: 992 },
  { id: 210, isoCode: "TZ", nameCapitalized: "TANZANIA, UNITED REPUBLIC OF", name: "Tanzania, United Republic of", iso3Code: "TZA", isoNumCode: 834, phoneCode: 255 },
  { id: 211, isoCode: "TH", nameCapitalized: "THAILAND", name: "Thailand", iso3Code: "THA", isoNumCode: 764, phoneCode: 66 },
  { id: 212, isoCode: "TL", nameCapitalized: "TIMOR-LESTE", name: "Timor-Leste", iso3Code: null, isoNumCode: null, phoneCode: 670 },
  { id: 213, isoCode: "TG", nameCapitalized: "TOGO", name: "Togo", iso3Code: "TGO", isoNumCode: 768, phoneCode: 228 },
  { id: 214, isoCode: "TK", nameCapitalized: "TOKELAU", name: "Tokelau", iso3Code: "TKL", isoNumCode: 772, phoneCode: 690 },
  { id: 215, isoCode: "TO", nameCapitalized: "TONGA", name: "Tonga", iso3Code: "TON", isoNumCode: 776, phoneCode: 676 },
  { id: 216, isoCode: "TT", nameCapitalized: "TRINIDAD AND TOBAGO", name: "Trinidad and Tobago", iso3Code: "TTO", isoNumCode: 780, phoneCode: 1868 },
  { id: 217, isoCode: "TN", nameCapitalized: "TUNISIA", name: "Tunisia", iso3Code: "TUN", isoNumCode: 788, phoneCode: 216 },
  { id: 218, isoCode: "TR", nameCapitalized: "TURKEY", name: "Turkey", iso3Code: "TUR", isoNumCode: 792, phoneCode: 90 },
  { id: 219, isoCode: "TM", nameCapitalized: "TURKMENISTAN", name: "Turkmenistan", iso3Code: "TKM", isoNumCode: 795, phoneCode: 7370 },
  { id: 220, isoCode: "TC", nameCapitalized: "TURKS AND CAICOS ISLANDS", name: "Turks and Caicos Islands", iso3Code: "TCA", isoNumCode: 796, phoneCode: 1649 },
  { id: 221, isoCode: "TV", nameCapitalized: "TUVALU", name: "Tuvalu", iso3Code: "TUV", isoNumCode: 798, phoneCode: 688 },
  { id: 222, isoCode: "UG", nameCapitalized: "UGANDA", name: "Uganda", iso3Code: "UGA", isoNumCode: 800, phoneCode: 256 },
  { id: 223, isoCode: "UA", nameCapitalized: "UKRAINE", name: "Ukraine", iso3Code: "UKR", isoNumCode: 804, phoneCode: 380 },
  { id: 224, isoCode: "AE", nameCapitalized: "UNITED ARAB EMIRATES", name: "United Arab Emirates", iso3Code: "ARE", isoNumCode: 784, phoneCode: 971 },
  { id: 225, isoCode: "GB", nameCapitalized: "UNITED KINGDOM", name: "United Kingdom", iso3Code: "GBR", isoNumCode: 826, phoneCode: 44 },
  { id: 226, isoCode: "US", nameCapitalized: "UNITED STATES", name: "United States", iso3Code: "USA", isoNumCode: 840, phoneCode: 1 },
  { id: 227, isoCode: "UM", nameCapitalized: "UNITED STATES MINOR OUTLYING ISLANDS", name: "United States Minor Outlying Islands", iso3Code: null, isoNumCode: null, phoneCode: 1 },
  { id: 228, isoCode: "UY", nameCapitalized: "URUGUAY", name: "Uruguay", iso3Code: "URY", isoNumCode: 858, phoneCode: 598 },
  { id: 229, isoCode: "UZ", nameCapitalized: "UZBEKISTAN", name: "Uzbekistan", iso3Code: "UZB", isoNumCode: 860, phoneCode: 998 },
  { id: 230, isoCode: "VU", nameCapitalized: "VANUATU", name: "Vanuatu", iso3Code: "VUT", isoNumCode: 548, phoneCode: 678 },
  { id: 231, isoCode: "VE", nameCapitalized: "VENEZUELA", name: "Venezuela", iso3Code: "VEN", isoNumCode: 862, phoneCode: 58 },
  { id: 232, isoCode: "VN", nameCapitalized: "VIET NAM", name: "Viet Nam", iso3Code: "VNM", isoNumCode: 704, phoneCode: 84 },
  { id: 233, isoCode: "VG", nameCapitalized: "VIRGIN ISLANDS, BRITISH", name: "Virgin Islands, British", iso3Code: "VGB", isoNumCode: 92, phoneCode: 1284 },
  { id: 234, isoCode: "VI", nameCapitalized: "VIRGIN ISLANDS, U.S.", name: "Virgin Islands, U.s.", iso3Code: "VIR", isoNumCode: 850, phoneCode: 1340 },
  { id: 235, isoCode: "WF", nameCapitalized: "WALLIS AND FUTUNA", name: "Wallis and Futuna", iso3Code: "WLF", isoNumCode: 876, phoneCode: 681 },
  { id: 236, isoCode: "EH", nameCapitalized: "WESTERN SAHARA", name: "Western Sahara", iso3Code: "ESH", isoNumCode: 732, phoneCode: 212 },
  { id: 237, isoCode: "YE", nameCapitalized: "YEMEN", name: "Yemen", iso3Code: "YEM", isoNumCode: 887, phoneCode: 967 },
  { id: 238, isoCode: "ZM", nameCapitalized: "ZAMBIA", name: "Zambia", iso3Code: "ZMB", isoNumCode: 894, phoneCode: 260 },
  { id: 239, isoCode: "ZW", nameCapitalized: "ZIMBABWE", name: "Zimbabwe", iso3Code: "ZWE", isoNumCode: 716, phoneCode: 263 },
  { id: 240, isoCode: "RS", nameCapitalized: "SERBIA", name: "Serbia", iso3Code: "SRB", isoNumCode: 688, phoneCode: 381 },
  { id: 241, isoCode: "AP", nameCapitalized: "ASIA PACIFIC REGION", name: "Asia / Pacific Region", iso3Code: "0", isoNumCode: 0, phoneCode: 0 },
  { id: 242, isoCode: "ME", nameCapitalized: "MONTENEGRO", name: "Montenegro", iso3Code: "MNE", isoNumCode: 499, phoneCode: 382 },
  { id: 243, isoCode: "AX", nameCapitalized: "ALAND ISLANDS", name: "Aland Islands", iso3Code: "ALA", isoNumCode: 248, phoneCode: 358 },
  { id: 244, isoCode: "BQ", nameCapitalized: "BONAIRE, SINT EUSTATIUS AND SABA", name: "Bonaire, Sint Eustatius and Saba", iso3Code: "BES", isoNumCode: 535, phoneCode: 599 },
  { id: 245, isoCode: "CW", nameCapitalized: "CURACAO", name: "Curacao", iso3Code: "CUW", isoNumCode: 531, phoneCode: 599 },
  { id: 246, isoCode: "GG", nameCapitalized: "GUERNSEY", name: "Guernsey", iso3Code: "GGY", isoNumCode: 831, phoneCode: 44 },
  { id: 247, isoCode: "IM", nameCapitalized: "ISLE OF MAN", name: "Isle of Man", iso3Code: "IMN", isoNumCode: 833, phoneCode: 44 },
  { id: 248, isoCode: "JE", nameCapitalized: "JERSEY", name: "Jersey", iso3Code: "JEY", isoNumCode: 832, phoneCode: 44 },
  { id: 249, isoCode: "XK", nameCapitalized: "KOSOVO", name: "Kosovo", iso3Code: "---", isoNumCode: 0, phoneCode: 381 },
  { id: 250, isoCode: "BL", nameCapitalized: "SAINT BARTHELEMY", name: "Saint Barthelemy", iso3Code: "BLM", isoNumCode: 652, phoneCode: 590 },
  { id: 251, isoCode: "MF", nameCapitalized: "SAINT MARTIN", name: "Saint Martin", iso3Code: "MAF", isoNumCode: 663, phoneCode: 590 },
  { id: 252, isoCode: "SX", nameCapitalized: "SINT MAARTEN", name: "Sint Maarten", iso3Code: "SXM", isoNumCode: 534, phoneCode: 1 },
  { id: 253, isoCode: "SS", nameCapitalized: "SOUTH SUDAN", name: "South Sudan", iso3Code: "SSD", isoNumCode: 728, phoneCode: 211 },
];

async function main() {
  // Reserved platform organization — superAdmins belong to this org
  await prisma.organization.upsert({
    where: { id: "platform" },
    create: { id: "platform", name: "TrustCRM Platform", status: "active" },
    update: { name: "TrustCRM Platform" },
  });
  console.log("Seeded platform organization.");

  console.log("Seeding countries...");
  for (const country of countries) {
    await prisma.country.upsert({
      where: { id: country.id },
      update: {
        isoCode: country.isoCode,
        nameCapitalized: country.nameCapitalized,
        name: country.name,
        iso3Code: country.iso3Code,
        isoNumCode: country.isoNumCode,
        phoneCode: country.phoneCode,
      },
      create: {
        id: country.id,
        isoCode: country.isoCode,
        nameCapitalized: country.nameCapitalized,
        name: country.name,
        iso3Code: country.iso3Code,
        isoNumCode: country.isoNumCode,
        phoneCode: country.phoneCode,
      },
    });
  }
  console.log(`Seeded ${countries.length} countries.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
