import type { FastifyPluginAsync } from "fastify";
import { healthRoute } from "./health.js";
import { organizationRoutes } from "./organizations.js";
import { userRoutes } from "./users.js";
import { invitationRoutes } from "./invitations.js";
import { webhooksRouter } from "./webhooks.js";
import { conversationsRouter } from "./conversations.js";
import { messagesRouter } from "./messages.js";
import { contactsRouter } from "./contacts.js";
import { companiesRouter } from "./companies.js";
import { segmentsRouter } from "./segments.js";
import { templatesRouter } from "./templates.js";
import { campaignsRouter } from "./campaigns.js";
import { pipelinesRouter } from "./pipelines.js";
import { dealsRouter } from "./deals.js";
import { routingRouter } from "./routing.js";
import { aiRouter } from "./ai.js";
import { transcriptionsRouter } from "./transcriptions.js";
import { flowsRouter } from "./flows.js";
import { chatbotsRouter } from "./chatbots.js";
import { analyticsRouter } from "./analytics.js";
import { trustScoreRouter } from "./trust-score.js";
import { onboardingRouter } from "./onboarding.js";
import { searchRouter } from "./search.js";

export const routes: FastifyPluginAsync = async (fastify) => {
  await fastify.register(healthRoute);
  await fastify.register(organizationRoutes, { prefix: "/v1" });
  await fastify.register(userRoutes, { prefix: "/v1" });
  await fastify.register(invitationRoutes, { prefix: "/v1" });
  await fastify.register(webhooksRouter, { prefix: "/v1" });
  await fastify.register(conversationsRouter, { prefix: "/v1" });
  await fastify.register(messagesRouter, { prefix: "/v1" });
  await fastify.register(contactsRouter, { prefix: "/v1" });
  await fastify.register(companiesRouter, { prefix: "/v1" });
  await fastify.register(segmentsRouter, { prefix: "/v1" });
  await fastify.register(templatesRouter, { prefix: "/v1" });
  await fastify.register(campaignsRouter, { prefix: "/v1" });
  await fastify.register(pipelinesRouter, { prefix: "/v1" });
  await fastify.register(dealsRouter, { prefix: "/v1" });
  await fastify.register(routingRouter, { prefix: "/v1" });
  await fastify.register(aiRouter, { prefix: "/v1" });
  await fastify.register(transcriptionsRouter, { prefix: "/v1" });
  await fastify.register(flowsRouter, { prefix: "/v1" });
  await fastify.register(chatbotsRouter, { prefix: "/v1" });
  await fastify.register(analyticsRouter, { prefix: "/v1" });
  await fastify.register(trustScoreRouter, { prefix: "/v1" });
  await fastify.register(onboardingRouter, { prefix: "/v1/onboarding" });
  await fastify.register(searchRouter, { prefix: "/v1" });
};
