export type RoleKey = "admin" | "manager" | "agent" | "viewer";

export const DEFAULT_ROLE_PERMISSIONS: Record<RoleKey, Record<string, string>> = {
  admin: {
    contacts_access: "allow",
    "contacts_access@contacts_export": "allow",
    "contacts_access@contacts_add": "allow",
    "contacts_access@contacts_delete": "allow",
    "contacts_access@contacts_bulk_tag": "allow",
    "contacts_access@contacts_import": "allow",
    "contacts_access@contacts_manage_custom_fields": "allow",
    hide_phone_number: "allow",
    "hide_phone_number@hide_contact_fields": "allow",
    inbox_access: "allow",
    "inbox_access@inbox_all_conversations": "allow",
    "inbox_access@inbox_unassigned": "allow",
    "inbox_access@assigned_chats_only": "allow",
    campaigns_access: "allow",
    "campaigns_access@campaigns_create": "allow",
    "campaigns_access@campaigns_pause_resume": "allow",
    "campaigns_access@campaigns_abort": "allow",
    "campaigns_access@campaigns_archive": "allow",
    "campaigns_access@campaigns_delete": "allow",
    "campaigns_access@campaigns_export_report": "allow",
    "campaigns_access@campaigns_custom_reports": "allow",
    templates_access: "allow",
    "templates_access@templates_ai_buttons": "allow",
    "templates_access@templates_create": "allow",
    "templates_access@templates_edit": "allow",
    "templates_access@templates_delete": "allow",
    settings_access: "allow",
    "settings_access@settings_agents": "allow",
    "settings_access@settings_whatsapp": "allow",
    "settings_access@settings_api_key": "allow",
    "settings_access@settings_billing": "allow",
    "settings_access@settings_tags": "allow",
    analytics_access: "allow",
    "analytics_access@analytics_export": "allow",
    "analytics_access@analytics_agent_performance": "allow",
    automation_access: "allow",
    "automation_access@automation_export_report": "allow",
    "automation_access@automation_welcome_message": "allow",
    "automation_access@automation_bot_flows": "allow",
    "automation_access@automation_bot_replies": "allow",
  },

  manager: {
    contacts_access: "allow",
    "contacts_access@contacts_export": "allow",
    "contacts_access@contacts_add": "allow",
    "contacts_access@contacts_bulk_tag": "allow",
    "contacts_access@contacts_import": "allow",
    inbox_access: "allow",
    "inbox_access@inbox_all_conversations": "allow",
    "inbox_access@inbox_unassigned": "allow",
    campaigns_access: "allow",
    "campaigns_access@campaigns_create": "allow",
    "campaigns_access@campaigns_pause_resume": "allow",
    "campaigns_access@campaigns_abort": "allow",
    "campaigns_access@campaigns_archive": "allow",
    "campaigns_access@campaigns_delete": "allow",
    "campaigns_access@campaigns_export_report": "allow",
    templates_access: "allow",
    "templates_access@templates_create": "allow",
    "templates_access@templates_edit": "allow",
    settings_access: "allow",
    "settings_access@settings_agents": "allow",
    "settings_access@settings_tags": "allow",
    analytics_access: "allow",
    "analytics_access@analytics_export": "allow",
    "analytics_access@analytics_agent_performance": "allow",
    automation_access: "allow",
    "automation_access@automation_export_report": "allow",
    "automation_access@automation_welcome_message": "allow",
    "automation_access@automation_bot_replies": "allow",
  },

  agent: {
    contacts_access: "allow",
    "contacts_access@contacts_add": "allow",
    inbox_access: "allow",
    "inbox_access@inbox_unassigned": "allow",
    "inbox_access@assigned_chats_only": "allow",
    templates_access: "allow",
  },

  viewer: {
    contacts_access: "allow",
    inbox_access: "allow",
    "inbox_access@inbox_all_conversations": "allow",
    campaigns_access: "allow",
    templates_access: "allow",
    analytics_access: "allow",
    automation_access: "allow",
  },
};

/**
 * Built-in baseline permissions for a role. Used only when an org has NO
 * `role_permissions_<role>` VendorSetting row. Returns {} for roles with no
 * baseline (e.g. superAdmin — which bypasses all checks anyway).
 */
export function defaultsForRole(role: string): Record<string, string> {
  return DEFAULT_ROLE_PERMISSIONS[role as RoleKey] ?? {};
}
